version: "3"

services:
  evalhalla-backend:
    depends_on:
      - postgres
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        APP_ENV: ${APP_ENV}
    ports:
      - 5000:80
      - 5050:15672
    environment:
      - ENABLE_FRONT_END=${ENABLE_FRONT_END}
      - EVALHALLA_AMQP_USER=dev_inst
      - EVALHALLA_AMQP_PASSWORD=dev_inst
      - EVALHALLA_AMQP_VHOST=evalhalla
      - EVALHALLA_DATABASE_USER=${EVALHALLA_DATABASE_USER}
      - EVALHALLA_DATABASE_PASSWORD=${EVALHALLA_DATABASE_PASSWORD}
      - EVALHALLA_DATABASE_HOST=${EVALHALLA_DATABASE_HOST}
      - EVALHALLA_DATABASE_NAME=${EVALHALLA_DATABASE_NAME}
      - EVALHALLA_BASIC_AUTH_ENABLED=${EVALHALLA_BASIC_AUTH_ENABLED}
      - EVALHALLA_BASIC_AUTH_USERNAME=${EVALHALLA_BASIC_AUTH_USERNAME}
      - EVALHALLA_BASIC_AUTH_PASSWORD=${EVALHALLA_BASIC_AUTH_PASSWORD}
      - EVALHALLA_BASIC_AUTH_REALM=${EVALHALLA_BASIC_AUTH_REALM}
      - EVALHALLA_USE_SENTIMENT=True
  postgres:
    image: "postgres:11.6"
    environment:
      - POSTGRES_USER=postgresadmin
      - POSTGRES_PASSWORD=letmein
    volumes:
      - ./postgres:/var/lib/postgresqldata
    ports:
      - 5432:5432


